### ISSUE TITLE
"Expected a type" in DefaultSHKConfigurator.h

### ISSUE THREAD

**Issue by tspangler** [ShareKit/ShareKit#1000]
Hello,

I've added ShareKit to my project via CocoaPods (first 4.0.1, which I then removed and tried 3.0.2). Both versions are throwing six `Expected a type` errors in `DefaultSHKConfigurator.h`:

line 84: `- (UIColor *)instagramLetterBoxColor;`

lines 91 - 95:
```
- (UIColor*)barTintForView:(UIViewController*)vc;
- (UIColor*)formFontColor;
- (UIColor*)formBackgroundColor;
- (NSString*)modalPresentationStyleForController:(UIViewController *)controller;
- (NSString*)modalTransitionStyleForController:(UIViewController *)controller;
```
Additional notes:

1. The demo project compiles and runs fine.
2. I am opening the .xcworkspace file.
3. Under Build Phases > Compile Sources I have moved my configuration file to the top of the list.

Any ideas?

**Comment by VilemKurz** [comment]
Please update to 4.0.2.

**Comment by tspangler** [comment]
That worked. Thank you for the updated podspec!
