### ISSUE TITLE
Sharekit Error (Added as cocoapods)

### ISSUE THREAD

**Issue by mikolalv123** [ShareKit/ShareKit#1001]
Hi all,
I am getting error when i am trying to build project. I have followed documentation and added sharekit as cocoapods, but it does not work. I am getting linker errors. Can someone assist how to solve this:
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_DefaultSHKConfigurator", referenced from:
      _OBJC_CLASS_$_ShareKitDemoConfigurator in ShareKitDemoConfigurator.o
  "_OBJC_CLASS_$_FBRequestConnection", referenced from:
      objc-class-ref in SProductFacebook.o
  "_OBJC_CLASS_$_SHKConfiguration", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_SHKFacebook", referenced from:
      objc-class-ref in AppDelegate.o
      objc-class-ref in EditViewController.o
      objc-class-ref in SProductFacebook.o
  "_OBJC_CLASS_$_SHKFlickr", referenced from:
      objc-class-ref in EditViewController.o
  "_OBJC_CLASS_$_SHKInstagram", referenced from:
      objc-class-ref in EditViewController.o
  "_OBJC_CLASS_$_SHKItem", referenced from:
      objc-class-ref in EditViewController.o
  "_OBJC_CLASS_$_SHKTumblr", referenced from:
      objc-class-ref in EditViewController.o
  "_OBJC_CLASS_$_SHKTwitter", referenced from:
      objc-class-ref in EditViewController.o
  "_OBJC_METACLASS_$_DefaultSHKConfigurator", referenced from:
      _OBJC_METACLASS_$_ShareKitDemoConfigurator in ShareKitDemoConfigurator.o
  "_SHKAuthDidFinishNotification", referenced from:
      -[SProductFacebook init] in SProductFacebook.o
      -[SProductFacebook dealloc] in SProductFacebook.o

**Comment by VilemKurz** [comment]
have you imported the headers?
