### ISSUE TITLE
Facebook share view is dismissed on tapping Location

### ISSUE THREAD

**Issue by Patsky** [ShareKit/ShareKit#1002]
Hello,

When I share to Facebook and tap on Location, the Facebook share view is sometimes dismissed (the odds are 50% in my case - sometimes it happens after 2 or 3 seconds, when I am on Location view seeing the map).

The best way to recreate this issue is to tap on 'Location' asap (just after the fb share view is presented). I thought it may be related to the thumbnail image i.e. I tap my share button, the fb view is presented but  there is no thumbnail yet, I open Location and then the thumbnail image is loaded on the previous view so it dismisses the FB share view. This would also explain why it happens more often on bit.ly or feedproxy.google.com links (as it takes more time to fetch the image due to redirection)
However it happened a few times when the thumbnail image was already loaded and tapping on Location dismissed the view. So not 100% sure whether loading a thumbnail image may cause this issue 

**I am using:** 
device: iPhone 5s
OS: 8.1.3
ShareKit version: 4.0.2 (the same issue was on 3.0.0)

**my code:**
```objective-c
NSString* url = @"http://feedproxy.google.com/~r/MobileMarketingWatch/~3/ngpnz4U-1n0/";
NSString* shareMessage = [NSString stringWithFormat:@"some message"];
SHKItem* item = [SHKItem URL:[NSURL URLWithString:url] title:shareMessage contentType:SHKURLContentTypeWebpage];
SHKiOSFacebook* sharer = [[SHKiOSFacebook alloc] init];
[sharer setShareDelegate:self];
[sharer loadItem:item];
[sharer share];
```

**This is what I can see in console log:**
```
plugin com.apple.share.Facebook.post interrupted
plugin com.apple.share.Facebook.post invalidated
viewServiceDidTerminateWithError:: Error Domain=_UIViewServiceInterfaceErrorDomain Code=3 "The operation couldn’t be completed. (_UIViewServiceInterfaceErrorDomain error 3.)" UserInfo=0x174474fc0 {Message=Service Connection Interrupted}
<-[SHKSharer dealloc] SHKSharer.m:(50)> !!! Facebook sharer deallocated!!!
```

Any ideas?

Many thanks in advance

**Comment by VilemKurz** [comment]
I could replicate the issue. Though I think this should be posted on Apple's bug reporter. You can find this issue over the internet also experiencing people, who are not using ShareKit.

**Comment by Patsky** [comment]
Thanks Vilém, yeah I was afraid it might be Apple issue. Thanks once again for looking into it.
