### ISSUE TITLE
Error: ARC forbids Objective-C in...  (Added as cocoapods)

### ISSUE THREAD

**Issue by loginov** [ShareKit/ShareKit#1003]
![screen shot 2015-02-19 at 10 40 32](https://cloud.githubusercontent.com/assets/2863775/6263177/c5a82064-b823-11e4-8e32-f6f3fd33697a.png)

**Comment by VilemKurz** [comment]
duplicate of #996. Use search and update cocoa pods.

**Comment by loginov** [comment]
>>Using ShareKit (4.0.3)
Same error
