### ISSUE TITLE
Is still Other Linker Flags "-all_load" required? 

### ISSUE THREAD

**Issue by fmtekcan** [ShareKit/ShareKit#1010]
Hi,
I am using some other 3rd party libraries. If I use "-all_load" flag Xcode give me build errors.
Do I have to use this "-all_load" flag ? Can I use "-force_load" ?

**Comment by VilemKurz** [comment]
all_load and force_load were workarounds for buggy compiler. Should be sorted now, so you do not need these flags anymore. Going to update install guide too.
Here is more info http://stackoverflow.com/questions/2567498/objective-c-categories-in-static-library/2615407#2615407.
