### ISSUE TITLE
SHKiOSFacebook - Always blank text

### ISSUE THREAD

**Issue by middiu** [ShareKit/ShareKit#1012]
Hi Guys,
Since I have updated to iOS 8.3 now when I try to share something using SHKiOSFacebook I get always not text in the sharing popup text, even using the ShareKit-Demo app.

In the simulator it works correctly, only my iPhone6 is affected. Have a look a this image to understand better what i mean:
![ios simulator screen shot 26 apr 2015 9 34 22 pm](https://cloud.githubusercontent.com/assets/428032/7337029/0aee0eb0-ec5c-11e4-95aa-c8032fe97b5c.png)

the rest of the sharing services work fine.
Am I the only one with this problem? is it just a "device" problem?

I'm using last version available on cocoapods.

Thanks
Emilio

**Comment by emiliomarin** [comment]
Same thing is happening to me on my iPhone 6 using iOS 8.1

**Comment by middiu** [comment]
ok, at least I know my iPhone6 is bugged.
Later on today I'll test it on my old iPhone 4S

Anyone from the dev team have any idea about this?

**Comment by middiu** [comment]
Ok, I found out what the problem is...
Looks like that when the new Facebook App (v29) is installed the method "SLComposeViewController setInitialText" doesn't work properly.

This is not a ShareKit issue but Facebook app bug. Facebook team is working on it.

http://stackoverflow.com/questions/29925810/slservicetypefacebook-setinitialtext-is-not-working
https://developers.facebook.com/bugs/1632385646995079/
https://developers.facebook.com/bugs/962985360399542/

Cheers
