### ISSUE TITLE
No Build

### ISSUE THREAD

**Issue by jamso620** [ShareKit/ShareKit#1014]
Hi,

For me is good idea ShareKit, but no build, the problem is:

Undefined symbols for architecture armv7:
  "_uncompress", referenced from:
      _ccInflateCCZFile in ZipUtils.o
  "_gzopen", referenced from:
      _ccInflateGZipFile in ZipUtils.o
  "_inflateEnd", referenced from:
      _inflateMemoryWithHint in ZipUtils.o
  "_gzclose", referenced from:
      _ccInflateGZipFile in ZipUtils.o
  "_inflate", referenced from:
      _inflateMemoryWithHint in ZipUtils.o
  "_gzread", referenced from:
      _ccInflateGZipFile in ZipUtils.o
  "_inflateInit2_", referenced from:
      _inflateMemoryWithHint in ZipUtils.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please Help Me!!!

**Comment by VilemKurz** [comment]
sorry, not a sharekit problem, check ziputils
