### ISSUE TITLE
problem installing

### ISSUE THREAD

**Issue by jamso620** [ShareKit/ShareKit#1016]
Hi!

After performing the installation steps, I produce an error, that is:

Undefined symbols for architecture armv7:
  "_uncompress", referenced from:
      _ccInflateCCZFile in ZipUtils.o
  "_gzopen", referenced from:
      _ccInflateGZipFile in ZipUtils.o
  "_inflateEnd", referenced from:
      _inflateMemoryWithHint in ZipUtils.o
  "_gzclose", referenced from:
      _ccInflateGZipFile in ZipUtils.o
  "_inflate", referenced from:
      _inflateMemoryWithHint in ZipUtils.o
  "_gzread", referenced from:
      _ccInflateGZipFile in ZipUtils.o
  "_inflateInit2_", referenced from:
      _inflateMemoryWithHint in ZipUtils.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

What should I do? Please help me.

Jamso620

**Comment by VilemKurz** [comment]
Sorry, this does not look like a shareKit problem.
