### ISSUE TITLE
Cannot use web login for Facebook and Twitter

### ISSUE THREAD

**Issue by andrewschreiber** [ShareKit/ShareKit#1018]
The issue is that users must enter in their login details into iOS settings. There is no option for using the web login as a backup.

**Comment by neofly** [comment]
There is a option in DefaultSHKConfigurator to force web login as backup. Implement your own DefaultSHKConfigurator (see <https://github.com/ShareKit/ShareKit/wiki/Configuration>) and add these lines :

    - (NSNumber *)forcePreIOS6FacebookPosting
    {
        BOOL result = NO;
        //if they have an account on their device, then use it, but don't force a device level login
        if (NSClassFromString(@"SLComposeViewController")) {
            result = ![SLComposeViewController isAvailableForServiceType:SLServiceTypeFacebook];
        }
        return [NSNumber numberWithBool:result];
    }

These lines are commented in [DefaultSHKConfigurator](https://github.com/ShareKit/ShareKit/blob/master/Classes/ShareKit/Configuration/DefaultSHKConfigurator.m) at line 89-96.

**Comment by VilemKurz** [comment]
Correct answer, thank you, @neofly
