### ISSUE TITLE
@# Usage

### ISSUE THREAD

**Issue by xdream86** [ShareKit/ShareKit#1020]
I found a strange code macro  in SHKConfiguration.h file as follow:

```objective-c
#define SHKCONFIG(_CONFIG_KEY) [[SHKConfiguration sharedInstance] configurationValue:@#_CONFIG_KEY withObject:nil]
```

Who knows the @# symbol usage?

**Comment by VilemKurz** [comment]
It helps to translate macro argument to string constant, see https://gcc.gnu.org/onlinedocs/cpp/Stringification.html#Stringification
