### ISSUE TITLE
ShareKit Facebook Share Dialog Cancel Delegate Not Working

### ISSUE THREAD

**Issue by riksof-farhan** [ShareKit/ShareKit#1022]
I am using latest sharekit and cocoapods for my project, and using sharekit to share almost all social networks. Among all only facebook have some issues like pre-fill text( which I know it's on facebook side) and the one I am facing and it's freaking me out is the delegates are not working properly on ios 8+.
In SHKSharerDelegate at line 51.

```sharerFunc
- (void)sharerFinishedSending:(SHKSharer *)sharer
{
	if (!sharer.quiet)
		[self.activityIndicator displayCompleted:SHKLocalizedString(@"Saved!") forSharer:sharer];
}
```

Either I cancel or I tap on post I always end up on the above delegate.

Below is the code how I call the delegates..
Working fine on ios < 8.

```facebookSharing
-(void)onClickFacebook{
    SHKItem *item;    
    item = [SHKItem URL:[NSURL URLWithString:@"http://google.com"] title:@"" contentType:SHKShareTypeURL];
    SHKSharer = iosSharer = [[SHKiOSFacebook alloc] init];
    [iosSharer loadItem:item];
    iosSharer.shareDelegate = self;
    [iosSharer share]
}

- (void)sharerFinishedSending:(SHKSharer *)sharer{
    NSLog(@"Share Successful");
}

- (void)sharerCancelledSending:(SHKSharer *)sharer {
     NSLog(@"Share Cancelled");
} 
```

**Comment by VilemKurz** [comment]
Checked on iOS9 and it works as intended, cancel delegate method is called as usual. Make sure, that your delegate object is not deallocated prematurely.
