### ISSUE TITLE
InstagramOnly option is not working

### ISSUE THREAD

**Issue by krin-san** [ShareKit/ShareKit#1026]
I try to share images through Instagram app and configured custom `SHKConfigurator` to return `@YES` in appropriate method but iOS 8.3 constantly shows me the *application list*.

**Comment by krin-san** [comment]
#1025 not fixed this issue but is related to Instagram sharing.

**Comment by krin-san** [comment]
Now I see, most of apps show UIDocumentInteractionController even if only Instagram app can open `.igo` files.
It'll be awesome to find the way without presenting interaction controller, like in this blog post: http://blog.horizon.camera/post/102273431070/video-share-objc-ios-instagram

**Comment by VilemKurz** [comment]
Not a problem of ShareKit, for more info see http://stackoverflow.com/questions/29906710/sharekit-skip-share-sheet-ios-8-for-instagram
