### ISSUE TITLE
Non-native Facebook sharer won't request publish privs

### ISSUE THREAD

**Issue by tspangler** [ShareKit/ShareKit#1027]
I've installed ShareKit 4.0.4 as a pod. When using the non-native `SHKFacebook` sharer, ShareKit never seems to request write privileges and thus never works properly.

Here is the behavior I experience from a clean install:

1. I call `[SHKFacebook shareItem:item]` and my app switches me to the FB auth page in Safari.

(The auth page states, *This does not let the app post to Facebook." )

2. Click OK, get switched back to my app.

3. ShareKit FB share dialog pops up.

4. Click "Send to Facebook" and get sent back to Safari again for a split second. I can't see any page loaded in this time before I'm immediately switched back to my app.

5. Nothing ever gets posted.

And when I uncomment a particular NSLog in `SHKFacebook.m`, I see this:

```
2015-06-07 02:21:25.925 MyApp[53293:1620119] <-[SHKFacebook isAuthorized] SHKFacebook.m:(181)> session is authorized:<FBSession: 0x7f9223594e40, state: FBSessionStateOpen, loginHandler: 0x0, appID: MY_APP_ID, urlSchemeSuffix: , tokenCachingStrategy:<FBSessionTokenCachingStrategy: 0x7f9223594f50>, expirationDate: 2015-08-06 00:14:24 +0000, refreshDate: 2015-06-07 00:21:17 +0000, attemptedRefreshDate: 0000-12-30 00:00:00 +0000, permissions:(
    "public_profile"
)>
```
Notice - no write permissions! I haven't changed the `facebookWritePermissions` method at all in my configurator, either:

```
- (NSArray*)facebookWritePermissions {
    return [NSArray arrayWithObjects:@"publish_actions", nil];
}
```

**Comment by yakubbaev** [comment]
+1

**Comment by yakubbaev** [comment]
@tspangler did you find any workaround?

**Comment by tspangler** [comment]
@yakubbaev No, I ended up ditching ShareKit for Facebook and using the official SDK.

**Comment by yakubbaev** [comment]
it seems that Facebook doesn't require publish_actions permissions. 
From [docs](https://developers.facebook.com/docs/facebook-login/permissions/v2.3):
> Publishing via dialogs or social plugins does not require this permission. Do not request review of this permission if you're only using Share dialog, Feed Dialog, Message Dialog etc, or Social Plugins (e.g. the Like Button.)

**Comment by VilemKurz** [comment]
I have tested it with the demo app, publishing works ok. Can you try the demo, and check if you see similar page than in your app?
