### ISSUE TITLE
Integration problems

### ISSUE THREAD

**Issue by DiegoBS** [ShareKit/ShareKit#1034]
Hello,
I'm new with xCode and I want to integrate ShareKit in my project. I have followed step by step the install instructions (submodules part). I think that I have made all the steps correctly but when I try to do a build on my Ipad Mini 3 I have this error:

ld: warning: ignoring file /Users/DiegoB/Library/Developer/Xcode/DerivedData/naturapps-dluqryowicyxziavtodfullahzhd/Build/Products/Debug-iphoneos/libShareKit.a, file was built for archive which is not the architecture being linked (armv7): /Users/DiegoB/Library/Developer/Xcode/DerivedData/naturapps-dluqryowicyxziavtodfullahzhd/Build/Products/Debug-iphoneos/libShareKit.a
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_DefaultSHKConfigurator", referenced from:
      _OBJC_CLASS_$_NaturAppsSKConfigurator in NaturAppsSKConfigurator.o
  "_OBJC_METACLASS_$_DefaultSHKConfigurator", referenced from:
      _OBJC_METACLASS_$_NaturAppsSKConfigurator in NaturAppsSKConfigurator.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I'm sure that I haven't forgot any framework of the list and I have added all necessary stuff (User Header Ser Path (Submodules/**), Other Linker Flags (-ObjC -al_load), target Dependencies (Resouce bundle and Static Library), the frameworks DropboxSDK, FacebookSDK, etc).

I have been reading other post that talk about changes on project architectures (Build Active Architecture Only from YES to NO, Valid Architectures from arm64, armv7, armv7s to only armv7, armv7s) but nothing solves my problem.

Any idea what could be happening?

**Comment by DiegoBS** [comment]
I have found the solution. On the ShareKit project you have to change "Build Active Architecture Only" to NO in all Targets and not only on Static Library.

**Comment by VilemKurz** [comment]
I do not think you have to do this. Tried with the demo app, and it works great without this change. Moreover, your configurator was not found either. This seems that the host project had wrong setting - should be yes for debug, no for release. Can you confirm?
