### ISSUE TITLE
My own sharing view

### ISSUE THREAD

**Issue by learan** [ShareKit/ShareKit#1037]
Hi all...
In my app I have my own sharing view where user can type his text and after that push the button.
My problem is: I don't wanna show UIActionSheet with options. I want to gather information from my custom sharing form and share it right away after he has pressed the button
I use code 
SHKItem *item = [SHKItem image:[UIImage imageNamed:@"photo_full_215.jpg"] title:@"test"];
SHKSharer* sharer = [[NSClassFromString(@"SHKiOSFacebook") alloc]init];
[sharer loadItem:item];
[sharer share];
How can I achieve it ?

**Comment by VilemKurz** [comment]
Please refer to the autoshare question in [https://github.com/ShareKit/ShareKit/wiki/FAQ](https://github.com/ShareKit/ShareKit/wiki/FAQ)
