### ISSUE TITLE
Installationproblems

### ISSUE THREAD

**Issue by Bradan** [ShareKit/ShareKit#1038]
Hello,

If I do everything like shown on the Wiki (except that I couldn't see the images, they just don't load) to install ShareKit, it ends up with compile errors:

> In file included from {...}/iOSInterface.mm:59:
> In file included from ShareKit/Classes/ShareKit/Core/ShareKit.h:14:
> ShareKit/Classes/ShareKit/Core/SHKItem.h:130:23: error: unknown type name 'UIPrintInfoOutputType'
> @property (nonatomic) UIPrintInfoOutputType printOutputType;
>                       ^
> In file included from {...}/iOSInterface.mm:59:
> In file included from ShareKit/Classes/ShareKit/Core/ShareKit.h:15:
> In file included from ShareKit/Classes/ShareKit/UI/SHKActionSheet.h:29:
> ShareKit/Classes/ShareKit/Core/SHK.h:51:31: error: unknown type name 'UIViewController'
> @property (nonatomic, strong) UIViewController *currentView;
>                               ^
> ShareKit/Classes/ShareKit/Core/SHK.h:51:1: error: property with 'retain (or strong)' attribute must be of object type
> @property (nonatomic, strong) UIViewController *currentView;
> ^
> ShareKit/Classes/ShareKit/Core/SHK.h:52:31: error: unknown type name 'UIViewController'
> @property (nonatomic, strong) UIViewController *pendingView;
>                               ^
> ShareKit/Classes/ShareKit/Core/SHK.h:52:1: error: property with 'retain (or strong)' attribute must be of object type
> @property (nonatomic, strong) UIViewController *pendingView;
> ^
> ShareKit/Classes/ShareKit/Core/SHK.h:88:32: error: expected a type
> + (void)setRootViewController:(UIViewController *)vc;
>                                ^
> ShareKit/Classes/ShareKit/Core/SHK.h:91:29: error: expected a type
> - (void)showViewController:(UIViewController *)vc;
>                             ^
> ShareKit/Classes/ShareKit/Core/SHK.h:93:39: error: expected a type
> - (void)showStandaloneViewController:(UIViewController *)vc;
>                                       ^
> ShareKit/Classes/ShareKit/Core/SHK.h:95:4: error: expected a type
> - (UIViewController *)rootViewForUIDisplay;
>    ^
> ShareKit/Classes/ShareKit/Core/SHK.h:100:4: error: expected a type
> + (UIBarStyle)barStyle;
>    ^
> ShareKit/Classes/ShareKit/Core/SHK.h:101:4: error: expected a type
> + (UIModalPresentationStyle)modalPresentationStyleForController:(UIViewController *)controller;
>    ^
> ShareKit/Classes/ShareKit/Core/SHK.h:101:66: error: expected a type
> + (UIModalPresentationStyle)modalPresentationStyleForController:(UIViewController *)controller;
>                                                                  ^
> ShareKit/Classes/ShareKit/Core/SHK.h:102:4: error: expected a type
> + (UIModalTransitionStyle)modalTransitionStyleForController:(UIViewController *)controller;
>    ^
> ShareKit/Classes/ShareKit/Core/SHK.h:102:62: error: expected a type
> + (UIModalTransitionStyle)modalTransitionStyleForController:(UIViewController *)controller;
>                                                              ^
> In file included from {...}/iOSInterface.mm:59:
> In file included from ShareKit/Classes/ShareKit/Core/ShareKit.h:15:
> ShareKit/Classes/ShareKit/UI/SHKActionSheet.h:38:45: error: cannot find protocol declaration for 'UIActionSheetDelegate'
> @interface SHKActionSheet : UIActionSheet  <UIActionSheetDelegate>
>                                             ^
> ShareKit/Classes/ShareKit/UI/SHKActionSheet.h:38:29: error: cannot find interface declaration for 'UIActionSheet', superclass of 'SHKActionSheet'
> @interface SHKActionSheet : UIActionSheet  <UIActionSheetDelegate>

What do I do wrong?

**Comment by Bradan** [comment]
Solved it by adding UIKit/UIKit.h before including ShareKit.h, but that's not really nice. Now I still get these linker errors although I included every framework you mentioned:

> Undefined symbols for architecture i386:
>   "_FBErrorParsedJSONResponseKey", referenced from:
>       -[SHKFacebook FBRequestHandlerCallback:result:error:] in libFacebook.a(SHKFacebook.o)
>       -[SHKFacebook FBRequestHandlerCallback:result:error:] in libShareKit.a(SHKFacebook.o)
>       -[SHKFacebook FBRequestHandlerCallback:result:error:] in libFacebook.a(SHKFacebook.o)
>       -[SHKFacebook FBRequestHandlerCallback:result:error:] in libShareKit.a(SHKFacebook.o)
>   "_OBJC_CLASS_$_ALAssetsLibrary", referenced from:
>       objc-class-ref in libShareKit.a(SHKPhotoAlbum.o)
>   "_OBJC_CLASS_$_CMMotionManager", referenced from:
>       objc-class-ref in iOSInterface.o
>   "_OBJC_CLASS_$_DBRequest", referenced from:
>       objc-class-ref in libShareKit.a(SHKDropbox.o)
>   "_OBJC_CLASS_$_DBRestClient", referenced from:
>       objc-class-ref in libShareKit.a(SHKDropbox.o)
>   "_OBJC_CLASS_$_DBSession", referenced from:
>       objc-class-ref in libShareKit.a(SHKDropbox.o)
>   "_OBJC_CLASS_$_FBAppCall", referenced from:
>       objc-class-ref in libFacebook.a(SHKFacebook.o)
>       objc-class-ref in libShareKit.a(SHKFacebook.o)
>   "_OBJC_CLASS_$_FBAppEvents", referenced from:
>       objc-class-ref in libFacebook.a(SHKFacebook.o)
>       objc-class-ref in libShareKit.a(SHKFacebook.o)
>   "_OBJC_CLASS_$_FBRequestConnection", referenced from:
>       objc-class-ref in libFacebook.a(SHKFacebook.o)
>       objc-class-ref in libShareKit.a(SHKFacebook.o)
>   "_OBJC_CLASS_$_FBSession", referenced from:
>       objc-class-ref in libFacebook.a(SHKFacebook.o)
>       objc-class-ref in libShareKit.a(SHKFacebook.o)
>   "_OBJC_CLASS_$_FBSettings", referenced from:
>       objc-class-ref in libFacebook.a(SHKFacebook.o)
>       objc-class-ref in libShareKit.a(SHKFacebook.o)
>   "_OBJC_CLASS_$_GPPShare", referenced from:
>       objc-class-ref in libShareKit.a(SHKGooglePlus.o)
>   "_OBJC_CLASS_$_GPPSignIn", referenced from:
>       objc-class-ref in libShareKit.a(SHKGooglePlus.o)
>   "_OBJC_CLASS_$_GPPURLHandler", referenced from:
>       objc-class-ref in libShareKit.a(SHKGooglePlus.o)
>   "_OBJC_CLASS_$_GTLCollectionObject", referenced from:
>       _OBJC_CLASS_$_GTLYouTubeActivityListResponse in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_CLASS_$_GTLYouTubeChannelListResponse in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_CLASS_$_GTLYouTubeGuideCategoryListResponse in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_CLASS_$_GTLYouTubeInvideoPromotion in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_CLASS_$_GTLYouTubeLiveBroadcastListResponse in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_CLASS_$_GTLYouTubeLiveStreamListResponse in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_CLASS_$_GTLYouTubePlaylistItemListResponse in libShareKit.a(GTLYouTube_Sources.o)
>       ...
>   "_OBJC_CLASS_$_GTLObject", referenced from:
>       _OBJC_CLASS_$_GTLYouTubeAccessPolicy in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_CLASS_$_GTLYouTubeActivity in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_CLASS_$_GTLYouTubeActivityContentDetails in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_CLASS_$_GTLYouTubeActivityContentDetailsBulletin in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_CLASS_$_GTLYouTubeActivityContentDetailsChannelItem in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_CLASS_$_GTLYouTubeActivityContentDetailsComment in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_CLASS_$_GTLYouTubeActivityContentDetailsFavorite in libShareKit.a(GTLYouTube_Sources.o)
>       ...
>   "_OBJC_CLASS_$_GTLQuery", referenced from:
>       _OBJC_CLASS_$_GTLQueryYouTube in libShareKit.a(GTLYouTube_Sources.o)
>      (maybe you meant: _OBJC_CLASS_$_GTLQueryYouTube)
>   "_OBJC_CLASS_$_GTLService", referenced from:
>       _OBJC_CLASS_$_GTLServiceYouTube in libShareKit.a(GTLYouTube_Sources.o)
>      (maybe you meant: _OBJC_CLASS_$_GTLServiceYouTube)
>   "_OBJC_CLASS_$_GTLUploadParameters", referenced from:
>       objc-class-ref in libShareKit.a(SHKYouTube.o)
>   "_OBJC_CLASS_$_GTMOAuth2ViewControllerTouch", referenced from:
>       objc-class-ref in libShareKit.a(SHKYouTube.o)
>   "_OBJC_CLASS_$_LiveConnectClient", referenced from:
>       objc-class-ref in libShareKit.a(SHKOneNote.o)
>   "_OBJC_CLASS_$_Pinterest", referenced from:
>       objc-class-ref in libShareKit.a(SHKPinterest.o)
>   "_OBJC_METACLASS_$_GTLCollectionObject", referenced from:
>       _OBJC_METACLASS_$_GTLYouTubeActivityListResponse in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_METACLASS_$_GTLYouTubeChannelListResponse in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_METACLASS_$_GTLYouTubeGuideCategoryListResponse in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_METACLASS_$_GTLYouTubeInvideoPromotion in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_METACLASS_$_GTLYouTubeLiveBroadcastListResponse in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_METACLASS_$_GTLYouTubeLiveStreamListResponse in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_METACLASS_$_GTLYouTubePlaylistItemListResponse in libShareKit.a(GTLYouTube_Sources.o)
>       ...
>   "_OBJC_METACLASS_$_GTLObject", referenced from:
>       _OBJC_METACLASS_$_GTLYouTubeAccessPolicy in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_METACLASS_$_GTLYouTubeActivity in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_METACLASS_$_GTLYouTubeActivityContentDetails in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_METACLASS_$_GTLYouTubeActivityContentDetailsBulletin in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_METACLASS_$_GTLYouTubeActivityContentDetailsChannelItem in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_METACLASS_$_GTLYouTubeActivityContentDetailsComment in libShareKit.a(GTLYouTube_Sources.o)
>       _OBJC_METACLASS_$_GTLYouTubeActivityContentDetailsFavorite in libShareKit.a(GTLYouTube_Sources.o)
>       ...
>   "_OBJC_METACLASS_$_GTLQuery", referenced from:
>       _OBJC_METACLASS_$_GTLQueryYouTube in libShareKit.a(GTLYouTube_Sources.o)
>      (maybe you meant: _OBJC_METACLASS_$_GTLQueryYouTube)
>   "_OBJC_METACLASS_$_GTLService", referenced from:
>       _OBJC_METACLASS_$_GTLServiceYouTube in libShareKit.a(GTLYouTube_Sources.o)
>      (maybe you meant: _OBJC_METACLASS_$_GTLServiceYouTube)
> ld: symbol(s) not found for architecture i386
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
>

**Comment by Bradan** [comment]
Btw installation by cocoapod or how it is called is not possible, because of several errors. This is horribly annoying. I hope to get some help here, because I sat the whole day on this.

**Comment by Bradan** [comment]
Nevermind I installed it via cocopops or however it is called, but I had to make curl insecure for it, by replacing curl by a bash script running the original curl with -k in the parameters.

You should say that you need the Facebook API and so on, too. That's not really mentioned in the installation wiki page.

Also I have problems with sharing now. I don't have a view controller or such stuff. How can I share an image from an App without GUI (or well it has GUI, but I don't have access to it, as I am using SDL2 and it is a game where the GUI is self-written)?

**Comment by VilemKurz** [comment]
Sorry for install troubles, should be fixed now. About sharing with no UI - we call it autoshare, check [FAQ](https://github.com/ShareKit/ShareKit/wiki/FAQ). Please, let me know, if autoshare as described in faq is helpful to you.

**Comment by Bradan** [comment]
Is autoshare not sharing completely without UI? I want to open the sharekit UI, but without having a UI myself or without having access to my own UI (as a library is creating the UI for me and abstracting it away).

**Comment by VilemKurz** [comment]
Yeah, autoshare is complete without UI - now I understand more what you are after. ShareKit tries to find topmost view controller and present ShareKit's UI from there. If you want present ShareKit (or whatever UI in general) independently from the app's standard view hierarchy you can use a new UIWindow with some dumb rootViewController. The rootVC's only role will be to load ShareKit's UI. Btw, this is [how Apple presents alerts](http://stackoverflow.com/questions/26554894/how-to-present-uialertcontroller-when-not-in-a-view-controller/30941356#30941356) using UIAlertController.
