### ISSUE TITLE
Circular dependency problem is still present

### ISSUE THREAD

**Issue by s1ddok** [ShareKit/ShareKit#1041]
I bet this is not ok I'm forced to use older version of CocoaPods in order to be able to install this framework.

Is there really no way to fix this issue?

**Comment by orkenstein** [comment]
Same here. Which version you were able to use?

**Comment by s1ddok** [comment]
Well, I decided to load pods individually for each social network instead of messing up with cocoa pods versions.

**Comment by orkenstein** [comment]
@s1ddok  didn't catch your idea. Could you, please, clarify? Podfile sample would be great.

**Comment by s1ddok** [comment]
this way
>pod 'ShareKit/Core'
>pod 'ShareKit/Vkontakte’
>pod 'ShareKit/Twitter'
>pod 'ShareKit/Instagram'

**Comment by orkenstein** [comment]
Of course! Thanks
The only issue I have is a:
Undefined symbols for architecture x86_64:
```
"_OBJC_CLASS_$_Pinterest", referenced from:
 objc-class-ref in SHKPinterest.o
ld: symbol(s) not found for architecture x86_64
```
Got solution?

**Comment by VilemKurz** [comment]
Should be working again, can you try? Btw, you do not need 'ShareKit/Core' as this is implicitly used by all other subspecs. So this is enough:

>pod 'ShareKit/Vkontakte’
>pod 'ShareKit/Twitter'
>pod 'ShareKit/Instagram'
