### ISSUE TITLE
installation failure: 'Submodules/SDWebImage'

### ISSUE THREAD

**Issue by ondevchrisa** [ShareKit/ShareKit#1046]
I'm trying to install via these instructions as a git submodule: https://github.com/ShareKit/ShareKit/wiki/Installing-ShareKit
and I get this...
> git submodule update --init --recursive
Submodule path 'Submodules/OpenInChrome': checked out 'b5bca8b426d639607a95d9ab1227cb06fb5f5ba8'
Submodule path 'Submodules/PKMultipartInputStream': checked out '03361761dba2298a0adc85edd129f60139113a94'
Submodule path 'Submodules/Pocket-ObjC-SDK': checked out 'd421134c1b1009148c1e9c9aa35bb42fbfe27e0a'
Submodule path 'Submodules/SDWebImage': checked out '6698910fe12076bc25b4956fa09b311c94235dbe'
Cloning into 'Vendors/libwebp'...
fatal: http://git.chromium.org/webm/libwebp.git/info/refs not valid: is this a git repository?
Clone of 'http://git.chromium.org/webm/libwebp.git' into submodule path 'Vendors/libwebp' failed
Submodule path 'Submodules/UIActivityIndicator-for-SDWebImage': checked out 'b746d5188979d5550f0483249f5b7a0cdc35bca4'
Submodule path 'Submodules/buffer-ios-sdk': checked out 'f1f85d7558ca4b4a057de533dfe8d7afe58cdbb5'
Submodule path 'Submodules/evernote-ios-sdk': checked out '7bcbaa6ab295d7015458f451481b998fa9126f5d'
Submodule path 'Submodules/google-api-objectivec': checked out '2f9f1dda639ddbadfe0c6f85c203e3afafde855a'
Submodule path 'Submodules/google-toolbox-for-mac': checked out '5a50c2e3080cd6bc76716180075c24dfd1987ede'
Submodule path 'Submodules/iso-8601-date-formatter': checked out '8e99c31914c79ddbc983e7dc9c2462476970595a'
Submodule path 'Submodules/samtextview': checked out 'fcad93af64076959902d769d39a8348d08818550'
Submodule path 'Submodules/sskeychain': checked out '7f52639da0e0afd149d170e826ec8192f6fee7de'
Failed to recurse into submodule path 'Submodules/SDWebImage'

multiple errors in there, please help!
The full installation log follows...

Xcode 7.0
Deployment Target: 5.1
Base SDK: Latest iOS (9.0)

Step 1: Get ShareKit files

> git submodule add git://github.com/ShareKit/ShareKit.git Submodules/ShareKit
A git directory for 'Submodules/ShareKit' is found locally with remote(s):
  origin	git://github.com/ShareKit/ShareKit.git
If you want to reuse this local git directory instead of cloning again from
  git://github.com/ShareKit/ShareKit.git
use the '--force' option. If the local git directory is not the correct repo
or you are unsure what this means choose another name with the '--name' option.

NOTE: I tried this before, thus the conflict.

> git submodule add --force git://github.com/ShareKit/ShareKit.git Submodules/ShareKit
Reactivating local git directory for submodule 'Submodules/ShareKit'.

> git commit -m 'ShareKit added as submodule'
[ShareKit_with_submodules fe3f3c1] ShareKit added as submodule
 2 files changed, 4 insertions(+)
 create mode 100644 .gitmodules
 create mode 160000 Submodules/ShareKit

> cd Submodules/ShareKit
> git submodule update --init --recursive
Submodule path 'Submodules/OpenInChrome': checked out 'b5bca8b426d639607a95d9ab1227cb06fb5f5ba8'
Submodule path 'Submodules/PKMultipartInputStream': checked out '03361761dba2298a0adc85edd129f60139113a94'
Submodule path 'Submodules/Pocket-ObjC-SDK': checked out 'd421134c1b1009148c1e9c9aa35bb42fbfe27e0a'
Submodule path 'Submodules/SDWebImage': checked out '6698910fe12076bc25b4956fa09b311c94235dbe'
Cloning into 'Vendors/libwebp'...
fatal: http://git.chromium.org/webm/libwebp.git/info/refs not valid: is this a git repository?
Clone of 'http://git.chromium.org/webm/libwebp.git' into submodule path 'Vendors/libwebp' failed
Submodule path 'Submodules/UIActivityIndicator-for-SDWebImage': checked out 'b746d5188979d5550f0483249f5b7a0cdc35bca4'
Submodule path 'Submodules/buffer-ios-sdk': checked out 'f1f85d7558ca4b4a057de533dfe8d7afe58cdbb5'
Submodule path 'Submodules/evernote-ios-sdk': checked out '7bcbaa6ab295d7015458f451481b998fa9126f5d'
Submodule path 'Submodules/google-api-objectivec': checked out '2f9f1dda639ddbadfe0c6f85c203e3afafde855a'
Submodule path 'Submodules/google-toolbox-for-mac': checked out '5a50c2e3080cd6bc76716180075c24dfd1987ede'
Submodule path 'Submodules/iso-8601-date-formatter': checked out '8e99c31914c79ddbc983e7dc9c2462476970595a'
Submodule path 'Submodules/samtextview': checked out 'fcad93af64076959902d769d39a8348d08818550'
Submodule path 'Submodules/sskeychain': checked out '7f52639da0e0afd149d170e826ec8192f6fee7de'
Failed to recurse into submodule path 'Submodules/SDWebImage'

**Comment by VilemKurz** [comment]
This looks like a problem with SDWebImage dependencies. Try `git submodule sync`, then `git submodule update --init --recursive`. Let me know, if it helped, please
