### ISSUE TITLE
Unable to find a specification for `Sharekit/GooglePlus`

### ISSUE THREAD

**Issue by weakfl** [ShareKit/ShareKit#1049]
I get this error when trying to install ShareKit via CocoaPods:

```
$ pod install
Updating local specs repositories
Analyzing dependencies
[!] Unable to find a specification for `Sharekit/GooglePlus`
```

Here's what I have in my podfile:
```
pod 'ShareKit/Core'
pod 'ShareKit/Facebook'
pod 'ShareKit/Twitter'
pod 'Sharekit/GooglePlus'
```

Any idea what's going wrong?

**Comment by VilemKurz** [comment]
Fixed, it had to be disabled, due to incopatibility with Youtube subspec. Now both sharers are working again
