### ISSUE TITLE
Include of non-modular header inside framework module 'FacebookSDK.FBAppLinkResolver'

### ISSUE THREAD

**Issue by LtrDan** [ShareKit/ShareKit#1055]
Installed latest pod with 'use_frameworks' on top...
can compile... this is the error i got:
Pods/Facebook-iOS-SDK/src/FBAppLinkResolver.h:19:9: Include of non-modular header inside framework module 'FacebookSDK.FBAppLinkResolver'

**Comment by VilemKurz** [comment]
Closing, this is a problem of Facebook's sdk
