### ISSUE TITLE
UIActivityIndicator-for-SDWebImage file missing

### ISSUE THREAD

**Issue by Lopdo** [ShareKit/ShareKit#1058]
I have installed ShareKit using CocoaPods, using only 'ShareKit/Facebook' and 'ShareKit/Twitter' and when I try to compile the project, it complains that:

/Pods/ShareKit/Classes/ShareKit/UI/SHKFormFieldLargeTextSettings.m:12:9: 'UIActivityIndicator-for-SDWebImage/UIImageView+UIActivityIndicatorForSDWebImage.h' file not found

From what I understand, UIActivityIndicator-for-SDWebImage is dependency of ShareKit and ShareKit should handle proper import of this class. Is that right or did I mess up somehow? I am still bit new to the pods

**Comment by joernschmidt** [comment]
Same problem here using Facebook and Whatsapp. Do I have to add another Sharkit component to the Podfile? Adding UIActivityIndicator-for-SDWebImage to the Podfile itself does not solve the problem.

**Comment by mrchristopher124** [comment]
This seems to be due to using use_frameworks! in a Podfile. I used to not use this for a project and recently switched and then ran into this issue.

**Comment by annphan** [comment]
Got the same issue with cocoapods 1.1.1

**Comment by joanromano** [comment]
Hi, check my issue for a workaround https://github.com/ShareKit/ShareKit/issues/1067#issuecomment-271582432 I believe we should use a better module name though
