### ISSUE TITLE
UIKit issue

### ISSUE THREAD

**Issue by NLSVTN** [ShareKit/ShareKit#1063]
In SHKItem (and other files too) it writes that UIKit is not present. Adding .pch file not working, adding UIKit directly to SHKItem does not work either (at least through pod) installation. I needed to abandon the idea of using ShareKit at all. It has soooo many unresolved issues!

**Comment by VilemKurz** [comment]
Sorry to hear this, and sorry for letting ShareKit without attention for this long. I am working on update, and even tried to use ShareKit from swift project, and this UIKit error is gone now.
