### ISSUE TITLE
Fix SHKFormFieldLargeTextSettings import for dynamic frameworks

### ISSUE THREAD

**Issue by joanromano** [ShareKit/ShareKit#1067]
Integrating this pod for dynamic frameworks with Xcode 7.3.1 has a broken header since I believe the behavior changed in this Xcode version and so the module name is being imported with an `_` instead of a `-`, thus not compiling anymore.

I guess we would have to update the import there to `#import <UIActivityIndicator_for_SDWebImage/UIImageView+UIActivityIndicatorForSDWebImage.h>` (my workaround for now) or just use a better module name?

**Comment by annphan** [comment]
@joanromano Finally, what solution to make this issue work? Thank you!

**Comment by joanromano** [comment]
@annphan check my comment, `update the import there to #import <UIActivityIndicator_for_SDWebImage/UIImageView+UIActivityIndicatorForSDWebImage.h> (my workaround for now) or just use a better module name`

**Comment by annphan** [comment]
Thank you so much @joanromano It works now

**Comment by dchatry** [comment]
This solves the issue I was having as well.

#1058 seems to be related.
