### ISSUE TITLE
SSKeychain is deprecated

### ISSUE THREAD

**Issue by K-Be** [ShareKit/ShareKit#1071]
SSKeychain has conflict with part of ios SDK.
The owner of the SSKeychain  renamed it to SAMKeychain 
[A issue about this](https://github.com/soffes/SAMKeychain/issues/154)

**Comment by VilemKurz** [comment]
This is now fixed in ShareKit itself, but Pinterest and Evernote are still using the old SSKeychain. Closing, as this is not possible to fix completely at the moment.
