### ISSUE TITLE
Expected method to read dictionary element not found on object of type 'id<FBOpenGraphObject>'

### ISSUE THREAD

**Issue by StjepanPoljak** [ShareKit/ShareKit#1079]
This issue already exists, but somebody doing something about it would be great. Can we fix this or not?

**Comment by VilemKurz** [comment]
Hi, closing as this is a duplicate. Everybody is welcome to make pull requests, so, please, do it. I admit that I do not have enough time to take care of the lib, sorry for that. I can do code reviews though.
