### ISSUE TITLE
sharekit.bundle no such file or directory

### ISSUE THREAD

**Issue by MoathOthman** [ShareKit/ShareKit#442]
hi ,

am trying to archive my application and am using the latest sharekit 2.0 

when i build for simulator or device everything is ok but when I try to archive in order to submit my app to the appstore i get this error

error: /Users/apple/Library/Developer/Xcode/DerivedData/DdadDreams-ergflklqirmouxdrexefidmgzhdo/ArchiveIntermediates/DdadDreams/BuildProductsPath/Release-iphoneos/ShareKit.bundle: No such file or directory

plz any help

**Comment by PhucDuy** [comment]
I try to install ShareKit by cocoapods and I get same issue.
