### ISSUE TITLE
Sharing to Vk.com is not working properly every time.

### ISSUE THREAD

**Issue by ExtremeMan** [ShareKit/ShareKit#606]
Hi,

I have found an issue with  Vk Sharer. I am receiving error when trying to share URL:
`"User authorization failed: access_token was given to another ip address."` with `error_code = 5`.

I was trying to fix that issue somehow and found next solution but I am not sure that it is correct way to fix 
authorization fails so I am not ready to pull it. 

The code below is doing next:
1) if error_code from Vk API is 5 then I am flushing access token 
2) Then I am prompting authorization that in some cases show login screen and in others just update access token.
3) By setting `self.pendingAction = SHKPendingShare` I am saying that sharing process should be finished.

What do you think about this? Could be there an authorization error infinite loop? May be someone could suggest better solution?

```
   // in the SHKVkontakte.m: sendTextAndLink method
   if ([[[result objectForKey:@"error"] objectForKey:@"error_code"] integerValue] == 5)
    {
        // user authorization failed
        SHKLog(@"User authorization failed: access_token was given to another ip address.");
        [[self class] flushAccessToken];

        [self promptAuthorization];
        self.pendingAction = SHKPendingShare;
        return YES;
    }
```

**Comment by zhangliang10** [comment]
> access_token in VK.com depend on the first three digits of the ip address. To disable this, try to set scope=offline in your request. Check the SHKVkontakteOAuthView.m file for request URL.

great ,Thanks
