### ISSUE TITLE
Demo Project not working

### ISSUE THREAD

**Issue by anuragkabra** [ShareKit/ShareKit#739]
error: /Users/playcez/Downloads/ShareKit-master/Classes/ShareKit/Sharers/Services/Buffer/../../../../../Submodules/buffer-ios-sdk/BufferSDK/BufferSDKResources.bundle: No such file or directory

**Comment by efulgencio** [comment]
Thanks ghost. I have the same problem.

**Comment by efulgencio** [comment]
The step 3. add ShareKit's "Resource Bundle" to your project's Copy Bundle Resources ... I don't find Sharekit.bundle

**Comment by efulgencio** [comment]
I download the project but I find empty directory ( Pocket-ObjC-SDK ) sample.
