### ISSUE TITLE
ShareKit fails to build with 64-bit target

### ISSUE THREAD

**Issue by hneil** [ShareKit/ShareKit#891]
ShareKit fails to build with a 64-bit target.  I've confirmed that the demo app fails in the same way.  Here's the output from the linker:
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_LiveConnectClient", referenced from:
      objc-class-ref in libShareKit.a(SHKOneNote.o)
ld: symbol(s) not found for architecture x86_64

Seems to be OneNote causing the problem.

**Comment by kapilmanak** [comment]
What release it has been fixed?
