### ISSUE TITLE
Cannot compile with pods

### ISSUE THREAD

**Issue by sportsy** [ShareKit/ShareKit#962]
I'm running into a problem when I installed the cocoapod. I'm currently using the latest version 3.0.0

When trying to compile. I receive this error. 

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_Pinterest", referenced from:
      objc-class-ref in libPods-Sportsy Beta.a(SHKPinterest.o)
  "_OBJC_CLASS_$_LiveConnectClient", referenced from:
      objc-class-ref in libPods-Sportsy Beta.a(SHKOneNote.o)
  "_OBJC_CLASS_$_GPPURLHandler", referenced from:
      objc-class-ref in libPods-Sportsy Beta.a(SHKGooglePlus.o)
  "_OBJC_CLASS_$_GPPSignIn", referenced from:
      objc-class-ref in libPods-Sportsy Beta.a(SHKGooglePlus.o)
  "_OBJC_CLASS_$_DBRestClient", referenced from:
      objc-class-ref in libPods-Sportsy Beta.a(SHKDropbox.o)
  "_OBJC_CLASS_$_DBSession", referenced from:
      objc-class-ref in libPods-Sportsy Beta.a(SHKDropbox.o)
  "_OBJC_CLASS_$_GPPShare", referenced from:
      objc-class-ref in libPods-Sportsy Beta.a(SHKGooglePlus.o)
  "_OBJC_CLASS_$_DBRequest", referenced from:
      objc-class-ref in libPods-Sportsy Beta.a(SHKDropbox.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by VilemKurz** [comment]
seems dead, closing

**Comment by orkenstein** [comment]
Getting the same on `pod 'ShareKit/Pinterest' 4.0.4`
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Pinterest", referenced from:
      objc-class-ref in SHKPinterest.o
ld: symbol(s) not found for architecture x86_64
```
