### ISSUE TITLE
Mail composer is automatically dismissed in iOS 8

### ISSUE THREAD

**Issue by appdog** [ShareKit/ShareKit#968]
When presenting the mail composer it is automatically dismissed after a few seconds (only in iOS 8).

Debug output:
<MFMailComposeRemoteViewController: 0x79bc5e00> timed out waiting for fence barrier from com.apple.MailCompositionService
<-[SHK keepSharerReference:] SHK.m:(108)> +++ Email reference
<-[SHK removeSharerReference:] SHK.m:(114)> --- Email reference
<-[SHKSharer dealloc] SHKSharer.m:(50)> !!! Email sharer deallocated!!!
viewServiceDidTerminateWithError: Error Domain=_UIViewServiceInterfaceErrorDomain Code=3 "The operation couldn’t be completed. (_UIViewServiceInterfaceErrorDomain error 3.)" UserInfo=0x7a32c490 {Message=Service Connection Interrupted}

**Comment by appdog** [comment]
Ok thanks for the feedback.

**Comment by alexcros** [comment]
Thanks for the info. 

Simulator 8.1 still crashes for now, I will redo my test with real device.

**Comment by Isuru-Nanayakkara** [comment]
It's 2016 and this issue still persists in iOS 9 simulators.
