### ISSUE TITLE
Circular dependency!

### ISSUE THREAD

**Issue by ackleymi** [ShareKit/ShareKit#983]
Im getting 

```
[!] There is a circular dependency between ShareKit/NoARC and ShareKit/Core
```

when trying to 'pod install' Sharekit/GooglePlus

What is going on?

**Comment by objectiveSee** [comment]
I am seeing this issues on cocoapods version 0.38.2.

**Comment by finalhit** [comment]
@objectiveSee Add `source 'https://github.com/CocoaPods/Specs.git'` at the top of Podfile

**Comment by csc-peteryuen** [comment]
@finalhit doesn't work, still has this `circular dependency` problem

**Comment by finalhit** [comment]
@objectiveSee You are right, the issue is still present. Kind of workaround is using some components only, e.g.:
```
source 'https://github.com/CocoaPods/Specs.git'

pod 'ShareKit/Core'
pod 'ShareKit/Facebook'
pod 'ShareKit/Twitter'
pod 'ShareKit/Instagram'
pod 'Facebook-iOS-SDK', '~> 3.2'
```

**Comment by OlegsKlujs** [comment]
Same on cocoapods 0.39.0

**Comment by e5faf2** [comment]
Same issue on cocoapods 0.38.2

**Comment by dchatry** [comment]
I get the error on every version of cocoapods (even with 0.34), I tried isolating only the components that I needed (as mentioned by @finalhit) but to no avail.
Is there any other solution to this issue?
