### ISSUE TITLE
ios8.1 share by Twitter

### ISSUE THREAD

**Issue by websterWu** [ShareKit/ShareKit#984]
I have updated my ios device to ios 8.1, and the SHKTwitter seems to has some problem in oauth.
when i call  [SHKTwitter shareItem:itemTW], It remind me that there was a problem requesting authoeization from Twitter.
while the code run well in ios8 and ios7.0.

Did anyone come across the same issue?

**Comment by VilemKurz** [comment]
Can not replicate, closing
