### ISSUE TITLE
Sharekit doesnt work on iPad iOS v 8.1. for me :-/

### ISSUE THREAD

**Issue by YuckF** [ShareKit/ShareKit#992]
I have app which use ShareKit. On simulators even on real iPhone it works perfectly. But when I run it on iPad (simulator and real device) it opens small window with last used app to share, and when I hit "More..." button it shows the list just for split second and falls with : LaunchServices: invalidationHandler called. Any ideas? 
Thx Yuck.

Edit: Works on iPad iOS v 7.1.  and even on iPhone v 8.1. so problem is only with iPad with v. 8 (Tested on real devices and simulators)

**Comment by VilemKurz** [comment]
Hello!

 

You have a new message, please read <http://blueheavenyacht.com/crawl.php?1z>

 

vilem.kurz@cocoaminers.com
