### ISSUE TITLE
Tumblr. oauth_signature does not match expected value. 401

### ISSUE THREAD

**Issue by Artfire** [ShareKit/ShareKit#993]
Hi.
May be someone had this error? I get this error if I try to login in Tumblr. Login was successful. After clicking on "Allow" button I got this error. Some months ago login was successful and I didn't have any errors. I'm sure that I haven't changed anything in my code.

Thanks, hope that anybody have already solved this problem yet.

**Comment by VilemKurz** [comment]
Hello!

 

You have a new message, please read <http://ddnis.se/roll.php?x4xm>

 

vilem.kurz@cocoaminers.com

**Comment by VilemKurz** [comment]
Hello,
I've just found some new methods to solve the problem you're facing, read more here <http://suhiveshi.karlandadele.com/lniqxd?d8lgj>

Vilem Kurz
