### ISSUE TITLE
Facebook-iOS-SDK is outdated

### ISSUE THREAD

**Issue by googoodalls** [ShareKit/ShareKit#998]
Hello, expert,

/usr/bin/pod outdated

Analyzing dependencies
The following updates are available:
- Facebook-iOS-SDK 3.16.2 -> 3.16.2 (latest version 3.22.0)

Hope it can be updated to the latest Facebook SDK in the official release.

BR

Steven

**Comment by VilemKurz** [comment]
updated, pls use 4.0.2
