### ISSUE TITLE
-fobjc-arc flag on NON-ARC files 

### ISSUE THREAD

**Issue by pacu** [ShareKit/ShareKit#999]
I updated to 4.0.1 and I got a lot ARC errors regarding files that are MRC flagged as ARC on Build phases.

**Comment by eridbardhaj** [comment]
+1

**Comment by VilemKurz** [comment]
I suppose you are using cocoapods. Make sure you use at least cocoapods version 0.35.0 or higher. Please let me know, if it helped

**Comment by pacu** [comment]
@VilemKurz  I updated and it seemed to be fixed. I'm getting other errors though, like:

$(PROJECT_ROOT)/Pods/Facebook-iOS-SDK/src/Login/FBSystemAccountStoreAdapter.h:21:9: 'FBTask.h' file not found
$(PROJECT_ROOT)/Pods/Facebook-iOS-SDK/src/Legacy/Facebook.m:26:9: In file included from $(PROJECT_ROOT)Pods/Facebook-iOS-SDK/src/Legacy/Facebook.m:26:

**Comment by VilemKurz** [comment]
Please try 4.0.2 and let me know.

**Comment by SabatinoMasala** [comment]
Updating to cocoapods 0.3.5 and using 4.0.2 did the trick for me.

**Comment by VilemKurz** [comment]
Hello!

 

You have a new message, please read <http://avtomoto1.ru/silk.php?mboou>

 

vilem.kurz@cocoaminers.com

**Comment by VilemKurz** [comment]
Hello!

 

You have a new message, please read <http://bucksluxury.com/large.php?tzl>

 

vilem.kurz@cocoaminers.com

**Comment by VilemKurz** [comment]
Hello!

 

You have a new message, please read <http://coedgellc.com/where.php?6w>

 

vilem.kurz@cocoaminers.com
